name: Print Software Versions

on:
  push:
    branches: [ laboratory-work-4 ]

jobs:
  # Робота 1: Перевірка мови (Java)
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version

  # Робота 2: Перевірка СКБД (PostgreSQL)
  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions] # Чекаємо завершення першої роботи
    steps:
      - name: Print PostgreSQL Version
        run: psql --version
