name: Print Software Versions
on:
  push:
    branches: main
jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version
  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Print PostgreSQL Version
        run: psql --version
