name: Program Code Linter
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  ProgramCodeLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Program Code
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVA: true
          FILTER_REGEX_INCLUDE: .*ProgramCode.java
          DISABLE_ERRORS: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
